import './globals.css';
import { Epilogue } from 'next/font/google';

const inter = Epilogue({ subsets: ['latin'] });

export const metadata = {
  title: 'snap',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
